---
- name: Install Choco and Firefox
  hosts: win
  tasks:
#   INSTALL CHOCO
    - name: install_chocolatey
      chocolatey.chocolatey.win_chocolatey:
        name: chocolatey -y
        state: present
      ignore_errors: yes
#   INSTALL FIREFOX
    - name: install_firefox
      chocolatey.chocolatey.win_chocolatey:
        name: firefox -y
        state: present