---
  # Update the name of the play
- name: Install web service
  hosts: all
  tasks:
      # Change the name of this task
    - name: Install service
      win_feature:
        name: Web-Server
        state: present

      # Change the name of this task
    - name: Start service
      win_service:
        name: W3Svc
        state: started

- name: The default web page is created on Win2016demo
  hosts: Win2016demo
  tasks:
      # Change the content of the file
    - name: Index file is created
      win_copy:
        content: "Hello World!"
        dest: C:\Inetpub\wwwroot\index.html

- name: The default web page is created on Win10demo
  hosts: Win10demo
  tasks:
      # Change the content of the file
    - name: Index file is created
      win_copy:
        content: "Hello World!"
        dest: C:\Inetpub\wwwroot\index.html
